### ISSUE TITLE
Add Deposit tab to Cashier

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#87]
Add the Deposit tab presentation al component to the Cashier Modal, as seen in the [Cashier Design Proposal](https://github.com/chips-blockchain/pangea-poker/issues/82#issuecomment-581773280) without linking it up to the backend.

### Sub-tasks: 
- [x] Add UI Elements
- [x] Add Copy to Clipboard feature
- [ ] Add icon next to the address section
- [x] Add tests

### Screens
[Figma Link](https://www.figma.com/file/L9nG96vciooI2p64PapYSbUi/Pangea-Poker?node-id=702%3A444)

![04-deposit](https://user-images.githubusercontent.com/17296915/73807070-1bdec300-47c3-11ea-93e5-a0d3fa5fa654.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73721488-47f33900-471c-11ea-8fa5-54da5acd2756.png">
