### ISSUE TITLE
Improve Modal accessibility

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#88]
Currently, the modal component is set of simple `div`elements. Instead, we should use an accessible modal component, for example, [react-modal](https://github.com/reactjs/react-modal).

### Sub-Tasks
- [x] Decide which solution to go with (react-modal)
- [x] Implement react-modal
- [x] Refactor Button placement so it's at a constant place
- [ ] Add tests
