### ISSUE TITLE
Add Withdraw tab to Cashier

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#89]
Add the Withdraw tab presentation al component to the Cashier Modal, as seen in the [Cashier Design Proposal](https://github.com/chips-blockchain/pangea-poker/issues/82#issuecomment-581773280) without linking it up to the backend.

This is `P2` for now, since we have work to do at the backend in order to figure out a secure way of withdrawing. We should be able to ship the Cashier feature without the withdrawal at first.

### Sub-tasks: 
- [x] #91: Separate Input component
- [x] Add UI Elements
- [x] Add Max amount feature
- [x] Add address validation
- [x] Design a confirmation step before withdrawal
- [x] Add tests

### Screens
[Figma Link](https://www.figma.com/file/L9nG96vciooI2p64PapYSbUi/Pangea-Poker?node-id=702%3A1385)

![05-withdraw](https://user-images.githubusercontent.com/17296915/73721692-bafcaf80-471c-11ea-85df-6cbef3c17a16.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73721832-fb5c2d80-471c-11ea-98b9-f6a5b6acda38.png">

**Comment by norbertdragan** [comment]
Closed by #160
