### ISSUE TITLE
Add Cashier Modal

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#90]
Add a Cashier Modal, as seen in the [Cashier Design Proposal](https://github.com/chips-blockchain/pangea-poker/issues/82#issuecomment-581773280).

### Sub-Tasks
- [x] #88: Switch to an accessible modal component
- [x] #87:  Add Deposit tab
- [x] #89: Add Withdraw tab 
- [X] Add Cashier button
- [x] #97: Link Deposit to the back-end
  - [x] Display correct balance
  - [x] Display correct address
- [x] Link Withdraw to the backend
  - [x] Display correct balance
  - [x] Execute withdrawal action
- [x] Display balance on the left of the UI

**Comment by piggydoughnut** [comment]
#302 - Display balance on the left of the UI
